### ISSUE TITLE
Normalization process shows this error "cannot find file"

### ISSUE THREAD

**Issue by justinjohn0306** [stanleyshly/EverybodyDanceNow#2]

**Comment by stanleyshly** [comment]
Did you run the rename cell before running the normalization cell? Also which normalization process are you running?

**Comment by justinjohn0306** [comment]
> Did you run the rename cell before running the normalization cell? Also which normalization process are you running?

this process...btw to prepare the dataset first I've gotta extract the stick figure and json then normalize them and then train or do I train the target vid first?

![jj](https://user-images.githubusercontent.com/34035011/108959121-fce6f380-7699-11eb-973c-f69cc786b2d7.PNG)

**Comment by stanleyshly** [comment]
You need to process with openpose then write labels and images before training. That cell doesn't work as expected, try the validation cell.

**Comment by justinjohn0306** [comment]
> You need to process with openpose then write labels and images before training. That cell doesn't work as expected, try the validation cell.
Let me run you through what I did so far...
1. Extracted images, pose and keypoints in json file format from both videos (Source and Target)
2. Renamed json for preparing files for train and val
3. Trained target on the network including FaceGAN
4. Normalization (TODO)
5. Results(TODO)

**Comment by stanleyshly** [comment]
Median smoothing is not yet working, but average smoothing is working.

**Comment by justinjohn0306** [comment]
what is the next step after training the target video? which cell do I run next? to generate the images?

![Capture](https://user-images.githubusercontent.com/34035011/110076527-a1f48100-7daa-11eb-9205-8f3aa8495684.PNG)

**Comment by stanleyshly** [comment]
Create your testing dataset, run EverybodyDanceNow Notebook file, mount to the drive, and run the test cell, and finally, run the ffmpeg cell.

**Comment by justinjohn0306** [comment]
> Create your testing dataset, run EverybodyDanceNow Notebook file, mount to the drive, and run the test cell, and finally, run the ffmpeg cell.

Thank you for the response. Finally got the results. Now if only I could normalize the stick figures...

**Comment by stanleyshly** [comment]
I'm working on fixing the normalization/designing a newer more simple process.

**Comment by justinjohn0306** [comment]
awesome!
