### ISSUE TITLE
It reports some error when running on colab.

### ISSUE THREAD

**Issue by henry-bugfree** [stanleyshly/EverybodyDanceNow#4]
Hello stanleyshly, I am a newbie to computer vision. Could you give me some advice how to run this program on google colab? I mean, when I run the '!python graph_train.py...' and '!python train_fullts.py...', it reports 'FileNotFoundError: [Errno 2] No such file or directory: '.../data/scratch/caroline/frames/jason_frames'' and '...AssertionError: MY_TRAINING_DATASET/train_label is not a valid directory'. I don't know if it is a problem of the datasets or the confirguration. I just want to run it successfully now. I would be very appreciated if you can reply.

**Comment by stanleyshly** [comment]
I just committed with some updated files, also, did you change the directory of the jason keypoints and frames to the directory of the mounted drive in the graph_train? Then check if the dataset folder(which you needed to upload to drive) has a train folder with labels and target images.

**Comment by stanleyshly** [comment]
Closed due to inactivity, please reopen if you have an update

**Comment by stanleyshly** [comment]
Closed due to inactivity, please reopen if you have an update
