### ISSUE TITLE
pose normalization code

### ISSUE THREAD

**Issue by carmelofascella** [stanleyshly/EverybodyDanceNow#6]
Hi, do you have the working pose normalization code "graph_posenorm.py" ?
I have tried your script and the one from the original folder, but they don't work.
In the Readme, it's written that you would have replaced it with a new working one.

Thank you!

**Comment by stanleyshly** [comment]
Unfortunately, I do not, the authors did no provide a working example. In the distance future, I have plans to write my own implementation, but that would not be anytime soon.
